[meta]
name = "Spectator Hotkeys"
author = "XertroV"
category = "Utilities"
version = "1.0.0"

[script]
dependencies = [ "MLHook", "MLFeedRaceData" ]
#__DEFINES__
# optional_dependencies = [ "Editor", "map-together" ]

